kondate/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls'), name='sign_up'),
    path('', include('kondate_app.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

kondate_app/urls.py
from django.conf.urls.static import static
from django.urls import path

from kondate import settings
from .views import StartView, RecipeUpdateView, RecipeDeleteView, today_menu_list, recipe_create

app_name = 'kondate_app'
urlpatterns = [
    path('', StartView.as_view(), name="start"),
    path('today/', today_menu_list, name="today"),
    path('create/', recipe_create, name="create"),
    path('update/<int:pk>', RecipeUpdateView.as_view(), name="update"),
    path('delete/<int:pk>', RecipeDeleteView.as_view(), name="delete"),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

kondate_app/models.py
from django.db import models
from django.utils import timezone
from accounts.models import CustomUser


class Recipe(models.Model):
    name = models.CharField(verbose_name='名前', max_length=100)
    user = models.ForeignKey(CustomUser, verbose_name='ユーザー',
                             on_delete=models.CASCADE,
                             related_name='recipe_user')
    comment = models.TextField(verbose_name='コメント', max_length=1000, null=True,
                               blank=True)
    image = models.ImageField(upload_to='images/%Y/%m/%d', verbose_name='写真',
                              height_field='url_height',
                              width_field='url_width',)
    url_height = models.IntegerField(editable=False,)
    url_width = models.IntegerField(editable=False,)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = 'レシピ'
        verbose_name_plural = 'レシピ'

    def __str__(self):
        return self.name


class RecipeIngredient(models.Model):
    name = models.CharField(verbose_name='材料', max_length=100)
    recipe = models.ForeignKey(Recipe, verbose_name='レシピ',
                               on_delete=models.CASCADE,
                               related_name="ingredient_Recipe")
    amount = models.CharField(verbose_name='数量', max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = '材料'
        verbose_name_plural = '材料'

    def __str__(self):
        return self.name


class RecipeProcess(models.Model):
    process = models.TextField(max_length=200)
    recipe = models.ForeignKey(Recipe, verbose_name='レシピ',
                               on_delete=models.CASCADE,
                               related_name='process_Recipe')
    # image = models.ImageField(upload_to='images/processes/%Y/%m/%d', verbose_name='写真',
    #                           height_field='url_height',
    #                           width_field='url_width',)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = '作り方'
        verbose_name_plural = '作り方'

    def __str__(self):
        return self.process


class Menu(models.Model):
    name = models.CharField(max_length=100, verbose_name='献立')
    recipe = models.ForeignKey(Recipe, verbose_name='レシピ', on_delete=models.CASCADE,
                               related_name='menu_recipe')
    date = models.DateField(verbose_name='日付', default=timezone.now)

    CATEGORY_CHOICES = [
        ('main_dish', '主菜'),
        ('side_dish', '副菜'),
        ('soup', '汁物'),
        ('rice', '飯物'),
        ('dessert', 'デザート'),
        ('drink', '飲み物'),
    ]

    category = models.CharField(verbose_name='カテゴリー',
                                choices=CATEGORY_CHOICES,
                                max_length=10,
                                default="main_dish")

    class Meta:
        verbose_name = '献立'
        verbose_name_plural = '献立'

    def __str__(self):
        return self.name


# class Recipe(models.Model):
#     name = models.CharField(verbose_name='名前', max_length=100)
#     # family = models.ForeignKey(Family, verbose_name='家族', on_delete=models.CASCADE,
#     #                            related_name="recipe_family")
#     user = models.ForeignKey(CustomUser, vorbose_name='ユーザー', on_delete=models.CASCADE,
#                              related_name='recipe_user')
#     # date = models.DateField(verbose_name='日付', default=timezone.now)
#     image = models.ImageField(upload_to='images/%Y/%m/%d', verbose_name='写真',
#                               height_field='url_height',
#                               width_field='url_width',)
#     url_height = models.IntegerField(editable=False,)
#     url_width = models.IntegerField(editable=False,)
#
#     # CATEGORY_CHOICES = [
#     #     ('main_dish', '主菜'),
#     #     ('side_dish', '副菜'),
#     #     ('soup', '汁物'),
#     #     ('rice', '飯物'),
#     #     ('dessert', 'デザート'),
#     #     ('drink', '飲み物'),
#     # ]
#     #
#     # category = models.CharField(verbose_name='カテゴリー',
#     #                             choices=CATEGORY_CHOICES,
#     #                             max_length=10,
#     #                             default="main_dish")
#     created_at = models.DateTimeField(auto_now_add=True)
#     updated_at = models.DateTimeField(auto_now=True)
#
#     class Meta:
#         verbose_name = 'Recipe'
#         verbose_name_plural = 'Recipe'
#
#     def __str__(self):
#         return self.name


# class Family(models.Model):
#     name = models.CharField(max_length=100)
#     created_at = models.DateTimeField(auto_now_add=True)
#     updated_at = models.DateTimeField(auto_now=True)
#
#     class Meta:
#         verbose_name = 'Family'
#         verbose_name_plural = 'Family'
#
#     def __str__(self):
#         return self.name

kondate_app/forms.py
from django import forms

from kondate_app.models import Recipe, RecipeIngredient, RecipeProcess


class RecipeCreateForm(forms.ModelForm):

    class Meta:
        model = Recipe
        fields = ('name', 'image', 'comment')


RecipeIngredientFormset = forms.inlineformset_factory(
    parent_model=Recipe,
    model=RecipeIngredient,
    form=RecipeCreateForm,
    fields=('name', 'amount'),
    extra=1,
    can_delete=False,
)

RecipeProcessFormset = forms.inlineformset_factory(
    parent_model=Recipe,
    model=RecipeProcess,
    form=RecipeCreateForm,
    fields=('process',),
    extra=1,
    can_delete=False,
)



# class RecipeCreateForm(forms.ModelForm):
#
#     class Meta:
#         model = Recipe
#         fields = ('name', 'date', 'image', 'category', )
#         # exclude = ('family',)
#
#         # def __init__(self, *args, **kwargs):
#         #     super().__init__(*args, **kwargs)
#         #     self.fields[0].widget.attrs["class"] = "name_field"

kondate_app/views.py
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.utils import timezone
from django.urls import reverse_lazy
from django.views.generic import TemplateView, DeleteView, UpdateView

from accounts.models import CustomUser
from .models import Recipe
from .forms import RecipeCreateForm, RecipeIngredientFormset, RecipeProcessFormset


class StartView(TemplateView):
    template_name = 'start.html'


def paginate_queryset(request, queryset, count):
    paginator = Paginator(queryset, count)
    page = request.GET.get('page')
    try:
        page_obj = paginator.page(page)
    except PageNotAnInteger:
        page_obj = paginator.page(1)
    except EmptyPage:
        page_obj = paginator.page(paginator.num_pages)
    return page_obj


@login_required()
def recipe_list(request):
    user = get_object_or_404(CustomUser, username=request.user)
    obj_list = user.recipe_user.all()
    posts = paginate_queryset(request, obj_list, 10)

    return render(request, 'recipe_list.html', {'posts': posts})


@login_required()
def today_menu_list(request):
    user_obj = get_object_or_404(CustomUser, username=request.user)
    recipe_obj = user_obj.recipe_user.all()
    if not recipe_obj:
        recipe_is_blank = True
        return render(request,
                      'today_menu.html',
                      {'recipe_is_blank': recipe_is_blank})

    today_menu = recipe_obj.menu_recipe.filter(date=timezone.now())

    main_dish = today_menu.filter(category="main_dish").first()
    side_dish = today_menu.filter(category="side_dish").first()
    soup = today_menu.filter(category="soup").first()
    rice = today_menu.filter(category="rice").first()
    dessert = today_menu.filter(category="dessert").first()
    drink = today_menu.filter(category="drink").first()

    return render(request,
                  'today_menu.html',
                  {
                      'main_dish': main_dish,
                      'side_dish': side_dish,
                      'soup': soup,
                      'rice': rice,
                      'dessert': dessert,
                      'drink': drink,
                  })


@login_required()
def recipe_create(request):
    form = RecipeCreateForm(request.POST, request.FILES)

    if request.method == 'POST' and form.is_valid():
        recipe = form.save(commit=False)
        recipe.user = request.user

        ingredient_formset = RecipeIngredientFormset(request.POST, instance=recipe)
        process_formset = RecipeProcessFormset(request.POST, instance=recipe)

        if ingredient_formset.is_valid() and process_formset.is_valid():
            recipe.save()
            ingredient_formset.save()
            process_formset.save()
            message = messages.success(request, "献立を作成しました。")
            return redirect('kondate_app:today')
        else:
            formset_error = ingredient_formset.errors
            context = {
                'formset_error': formset_error,
                'form': form,
                'ingredient_formsets': ingredient_formset,
                'process_formsets': process_formset,
            }
    else:
        form_error = form.errors
        context = {
            'form_error': form_error,
            'form': form,
            'ingredient_formsets': RecipeIngredientFormset(),
            'process_formsets': RecipeProcessFormset(),
        }

    return render(request, 'create_recipe.html', context)


class RecipeUpdateView(LoginRequiredMixin, UpdateView):
    model = Recipe
    template_name = 'update_Recipe.html'
    form_class = RecipeCreateForm
    success_url = reverse_lazy('kondate_app:today')

    def get_success_url(self):
        return reverse_lazy('kondate_app:today', kwargs={'pk': self.kwargs['pk']})

    def form_valid(self, form):
        messages.success(self.request, 'レシピを更新しました')
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, 'レシピの更新に失敗しました')
        return super(self).form_invalid(form)


class RecipeDeleteView(LoginRequiredMixin, DeleteView):
    model = Recipe
    template_name = 'delete_Recipe.html'
    success_url = reverse_lazy('kondate_app:today')

    def delete(self, request, *args, **kwargs):
        messages.success(self.request, "献立を削除しました")
        return super().delete(request, *args, **kwargs)

# @login_required()
# def today_list(request):
#     family_obj = CustomUser.objects.get(username=request.user).family
#     if not family_obj:
#         family_is_blank = True
#         return render(request, 'today_menu.html', {'family_is_blank': family_is_blank})
#
#     today_menu = family_obj.recipe_family.filter(date=timezone.now())
#     if not today_menu:
#         today_menu_is_blank = True
#         return render(request, 'today_menu.html', {'today_menu_is_blank': today_menu_is_blank})
#
#     main_dish = today_menu.filter(category="main_dish").first()
#     side_dish = today_menu.filter(category="side_dish").first()
#     soup = today_menu.filter(category="soup").first()
#     rice = today_menu.filter(category="rice").first()
#     dessert = today_menu.filter(category="dessert").first()
#     drink = today_menu.filter(category="drink").first()
#
#     return render(request, 'today_menu.html', {
#         'main_dish': main_dish,
#         'side_dish': side_dish,
#         'soup': soup,
#         'rice': rice,
#         'dessert': dessert,
#         'drink': drink,
#     })

kondate_app/templates/base.html
<!DOCTYPE html>
{% load static %}
{% load widget_tweaks %}
<html lang="ja">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Kondate | {% block title %}{% endblock %}</title>

  <!-- Bootstrap Core CSS -->
  <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

  <!-- Custom Fonts -->
  <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css">
  <link href="{% static 'vendor/simple-line-icons/css/simple-line-icons.css' %}" rel="stylesheet">

  <!-- Custom CSS -->
<!--  <link href="{% static 'css/stylish-portfolio.min.css' %}" rel="stylesheet">-->
    <link href="{% static 'css/stylish-portfolio.css' %}" rel="stylesheet">


</head>

<body id="page-top">

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
      {% if user.is_authenticated %}
      <a class="navbar-brand" href="{% url 'kondate_app:today' %}">Kondate</a>

      <ul class="navbar-nav">
        <li class="nav-item navbar-text text-primary" style="font-weight: bold; font-size: 20px; margin-right: 20px;">
            {{ user.get_username }}
        </li>
      </ul>

      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
              aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
        <ul class="navbar-nav">

          <li class="nav-item active">
            <a class="nav-link active" href="{% url 'kondate_app:today' %}">Home <span class="sr-only">(current)</span></a>
          </li>

          <li class="nav-item">
            <a class="nav-link active" href="#">About</a>
          </li>

          <li class="nav-item">
            <a class="nav-link active" href="#">献立</a>
          </li>

          <li class="nav-item">
            <a class="nav-link active" href="#">買い物</a>
          </li>

          <li class="nav-item">
            <a class="nav-link active" href="#">レシピ</a>
          </li>

          <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">マイページ</a>
        </li>

        <li class="nav-item">
          <a class="nav-link" aria-current="page" href="{% url 'account_logout' %}">ログアウト</a>
        </li>

    {% else %}

    <a class="navbar-brand" href="{% url 'kondate_app:start' %}">Kondate</a>
    {% endif %}

      </ul>
  </div>
</nav>

  {% block contents %}{% endblock %}

  <!-- Footer -->
  <footer class="footer text-center">
    <div class="container">
<!--      <ul class="list-inline mb-5">-->
<!--        <li class="list-inline-item">-->
<!--          <a class="social-link rounded-circle text-white mr-3" href="#!">-->
<!--            <i class="icon-social-facebook"></i>-->
<!--          </a>-->
<!--        </li>-->
<!--        <li class="list-inline-item">-->
<!--          <a class="social-link rounded-circle text-white mr-3" href="#!">-->
<!--            <i class="icon-social-twitter"></i>-->
<!--          </a>-->
<!--        </li>-->
<!--        <li class="list-inline-item">-->
<!--          <a class="social-link rounded-circle text-white" href="#!">-->
<!--            <i class="icon-social-github"></i>-->
<!--          </a>-->
<!--        </li>-->
      </ul>
      <p class="text-muted small mb-0">Copyright &copy; Kondate 2020</p>
    </div>
  </footer>

  <!-- Bootstrap core JavaScript -->
  <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  <!-- Plugin JavaScript -->
  <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>

  <!-- Custom scripts for this template -->
  <script src="{% static 'js/stylish-portfolio.min.js' %}"></script>

</body>

</html>

kondate_app/templates/create_recipe.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% load static %}

{% block title %}新規作成{% endblock %}

{% block contents %}
<div class="container">
    <div class="row">
        <div class="my-div-style w-50" style="margin-top: 100px;">
            <h2 class="m-4">レシピを登録</h2>
            <form method="post" enctype="multipart/form-data">
                <table class="table">

                    {{ ingredient_formsets.non_form_errors }}
                    {{ form.non_field_errors }}


                <!--form-->
                    <div class="form-group row">
                        <label for="{{ form.name.id_for_label }}" class="col-sm-3 col-form-label">レシピ名：</label>
                        <div class="col-sm-9">
                            <span class="help-block">{{ error }}</span>
                            {{ form.name|add_class:'form-name' }}

                        </div>
                    </div>

<!--                    <div class="form-group row">-->
<!--                        <label for="{{ form.date.id_for_label }}" class="col-sm-3 col-form-label">日時：</label>-->
<!--                        <div class="col-sm-9">-->
<!--                            <span class="help-block">{{ error }}</span>-->
<!--                            {{ form.date|add_class:'form-date' }}-->
<!--                        </div>-->
<!--                    </div>-->

                    <div class="form-group row">
                        <label for="{{ form.image.id_for_label }}" class="col-sm-3 col-form-label">写真：</label>
                        <div class="col-sm-9">
                            <span class="help-block">{{ error }}</span>
                            {{ form.image|add_class:'form-image' }}
                        </div>
                    </div>

                    <div class="form-group row">
                        <label for="{{ form.comment.id_for_label }}" class="col-sm-3 col-form-label">コメント：</label>
                        <div class="col-sm-9">
                            <span class="help-block">{{ error }}</span>
                            {{ form.comment|add_class:'form-comment' }}
                        </div>
                    </div>

<!--                    <div class="form-group row">-->
<!--                        <label for="{{ form.category.id_for_label }}" class="col-sm-3 col-form-label">カテゴリ：</label>-->
<!--                        <div class="col-sm-9">-->
<!--                            <span class="help-block">{{ error }}</span>-->
<!--                            {{ form.category|add_class:'class-name' }}-->
<!--                        </div>-->
<!--                    </div>-->


                <!--ingredient_formset-->
                    {% for ingredient_formset in ingredient_formsets %}
                    <div class="form-group row">
                        <label for="{{ ingredient_formset.name.id_for_label }}" class="col-sm-3 col-form-label">材料：</label>
                        {{ ingredient_formset.name|add_class:'ingredient_formset-name' }}
                    <!--{{ form.name.errors }}-->
                    </div>

                    <div class="form-group row">
                        <label for="{{ ingredient_formset.amount.id_for_label }}"  class="col-sm-3 col-form-label">数量：</label>
                        {{ ingredient_formset.amount|add_class:'ingredient_formset-amount' }}
                    <!--{{ form.amount.errors }}-->
                    </div>
                    {% endfor %}

                     {% for ingredient_field in ingredient_formset.hidden_fields %}
                        {{ ingredient_field }}
                    {% endfor %}

                    {{ ingredient_formsets.management_form }}

                <!--process_formset-->

                    {% for process_formset in process_formsets %}
                    <div class="form-group row">
                        <label for="{{ process_formset.name.id_for_label }}" class="col-sm-3 col-form-label">作り方：</label>
                        {{ process_formset.process|add_class:'process_formset-process' }}
                    <!--{{ form.name.errors }}-->
                    </div>

<!--                    <div class="form-group row">-->
<!--                        <label for="{{ process_formset.amount.id_for_label }}"  class="col-sm-3 col-form-label">数量：</label>-->
<!--                        {{ process_formset.number|add_class:'process_formset-number' }}-->
<!--                    &lt;!&ndash;{{ form.amount.errors }}&ndash;&gt;-->
<!--                    </div>-->
                    {% endfor %}

                     {% for process_field in process_formset.hidden_fields %}
                        {{ process_field }}
                    {% endfor %}

                    {{ process_formsets.management_form }}


                    {% csrf_token %}
                </table>
                <button class="btn btn-primary" type="submit">
                    作成
                </button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

kondate_app/templates/delete_menu.html
{% extends 'base.html' %}

{% block title %} 編集 {% endblock %}

{% block contents %}
<div class="container" style="margin-top: 100px;">
    <div class="row">
        <div class="mx-auto col-lg-8 col-md-10">

        <div class="my-div-style w-50" style="margin-top: 100px;">
            <h2 class="m-4">献立を編集</h2>
            <form method="post">
                {% csrf_token %}
                <table class="table">
                    {{ form.as_table }}
                </table>
                <p>本当に削除しますか？</p>
                <button class="btn btn-primary" type="submit">
                    削除
                </button>
                <a href="{% url 'kondate_app:today' %}" class="btn btn-secondary ml-2">キャンセル</a>
            </form>
        </div>
        </div>
    </div>

</div>
{% endblock %}

kondate_app/templates/delete_recipe.html
{% extends 'base.html' %}

{% block title %} 編集 {% endblock %}

{% block contents %}
<div class="container" style="margin-top: 100px;">
    <div class="row">
        <div class="mx-auto col-lg-8 col-md-10">

        <div class="my-div-style w-50" style="margin-top: 100px;">
            <h2 class="m-4">献立を編集</h2>
            <form method="post">
                {% csrf_token %}
                <table class="table">
                    {{ form.as_table }}
                </table>
                <p>本当に削除しますか？</p>
                <button class="btn btn-primary" type="submit">
                    削除
                </button>
                <a href="{% url 'kondate_app:today' %}" class="btn btn-secondary ml-2">キャンセル</a>
            </form>
        </div>
        </div>
    </div>

</div>
{% endblock %}

kondate_app/templates/list.html
{% extends 'base.html' %}

kondate_app/templates/today_menu.html
{% extends 'base.html' %}
{% load static %}
{% block title %}メインページ{% endblock %}

{% block contents %}
<div class="container" style="margin-top: 100px;">

        {% if today_menu_is_blank is True %}
            <h2>本日の献立がありません。<br>こちらから新しく献立を作成してください。</h2>
            <a class="btn btn-primary m-5" href="{% url 'kondate_app:create' %}">新しくレシピを作成する</a>
        {% else %}
            <a class="btn btn-primary float-right" href="{% url 'kondate_app:create' %}">新しくレシピを作成する</a>
            <div class="row">
                <div class="mx-auto col-lg-8 col-md-10">
                    <h2>ー本日の献立ー</h2>

                    {% if main_dish %}
                    <h4 class="border-bottom m-sm-5">主菜</h4>
                    <p>{{ main_dish.name }}</p>
                    {% endif %}

                    {% if side_dish %}
                    <h4 class="border-bottom m-sm-5">副菜</h4>
                    <p>{{ side_dish.name }}</p>
                    {% endif %}

                    {% if soup %}
                    <h4 class="border-bottom m-sm-5">汁物</h4>
                    <p>{{ soup.name }}</p>
                    {% endif %}

                    {% if rice %}
                    <h4 class="border-bottom m-sm-5">飯物</h4>
                    <p>{{ rice.name }}</p>
                    {% endif %}

                    {% if dessert %}
                    <h4 class="border-bottom m-sm-5">デザート</h4>
                    <p>{{ dessert.name }}</p>
                    {% endif %}

                    {% if drink %}
                    <h4 class="border-bottom m-sm-5">飲み物</h4>
                    <p>{{ drink.name }}</p>
                    {% endif %}
                </div>
            </div>
        {% endif %}
    {% endif %}
</div>
{% endblock contents %}

kondate_app/templates/today_recipe.html
{% extends 'base.html' %}
{% load static %}
{% block title %}メインページ{% endblock %}

{% block contents %}
<div class="container" style="margin-top: 100px;">

    {% if family_is_blank is True %}
        <h2>ご登録誠にありがとうございます。<br>使用開始に伴い、まずは家族の登録、<br>もしくは既存の家族への追加を行ってください。</h2>
    {% else %}
        {% if today_menu_is_blank is True %}
            <h2>本日の献立がありません。<br>こちらから新しく献立を作成してください。</h2>
            <a class="btn btn-primary m-5" href="{% url 'kondate_app:create' %}">新しくレシピを作成する</a>
        {% else %}
            <a class="btn btn-primary float-right" href="{% url 'kondate_app:create' %}">新しくレシピを作成する</a>
            <div class="row">
                <div class="mx-auto col-lg-8 col-md-10">
                    <h2>ー本日の献立ー</h2>

                    {% if main_dish %}
                    <h4 class="border-bottom m-sm-5">主菜</h4>
                    <p>{{ main_dish.name }}</p>
                    {% endif %}

                    {% if side_dish %}
                    <h4 class="border-bottom m-sm-5">副菜</h4>
                    <p>{{ side_dish.name }}</p>
                    {% endif %}

                    {% if soup %}
                    <h4 class="border-bottom m-sm-5">汁物</h4>
                    <p>{{ soup.name }}</p>
                    {% endif %}

                    {% if rice %}
                    <h4 class="border-bottom m-sm-5">飯物</h4>
                    <p>{{ rice.name }}</p>
                    {% endif %}

                    {% if dessert %}
                    <h4 class="border-bottom m-sm-5">デザート</h4>
                    <p>{{ dessert.name }}</p>
                    {% endif %}

                    {% if drink %}
                    <h4 class="border-bottom m-sm-5">飲み物</h4>
                    <p>{{ drink.name }}</p>
                    {% endif %}
                </div>
            </div>
        {% endif %}
    {% endif %}
</div>
{% endblock contents %}

kondate_app/templates/update_menu.html
{% extends 'base.html' %}

{% block title %} 編集 {% endblock %}

{% block contents %}
<div class="container" style="margin-top: 100px;">
    <div class="row">
        <div class="mx-auto col-lg-8 col-md-10">

        <div class="my-div-style w-50" style="margin-top: 100px;">
            <h2 class="m-4">献立を編集</h2>
            <form method="post">
                {% csrf_token %}
                <table class="table">
                    {{ form.as_table }}
                </table>
                <button class="btn btn-primary" type="submit">
                    更新
                </button>
                <a href="{% url 'kondate_app:today' %}" class="btn btn-secondary ml-2">キャンセル</a>
            </form>
        </div>
        </div>
    </div>

</div>
{% endblock %}

kondate_app/templates/update_recipe.html
{% extends 'base.html' %}

{% block title %} 編集 {% endblock %}

{% block contents %}
<div class="container" style="margin-top: 100px;">
    <div class="row">
        <div class="mx-auto col-lg-8 col-md-10">

        <div class="my-div-style w-50" style="margin-top: 100px;">
            <h2 class="m-4">献立を編集</h2>
            <form method="post">
                {% csrf_token %}
                <table class="table">
                    {{ form.as_table }}
                </table>
                <button class="btn btn-primary" type="submit">
                    更新
                </button>
                <a href="{% url 'kondate_app:today' %}" class="btn btn-secondary ml-2">キャンセル</a>
            </form>
        </div>
        </div>
    </div>

</div>
{% endblock %}